#!/bin/zsh
dir=$(dirname $0)

cp $dir/.zshrc ~/.zshrc

if [[ -e ~/.config/nvim.old ]] then
    rm -r ~/.config/nvim.old
fi
cp -r ~/.config/nvim ~/.config/nvim.old
rm -r ~/.config/nvim
cp -r $dir/nvim ~/.config
print "WARNING: The old ~/.config/nvim has been copied to ~/.config/nvim.old, and this backup will be deleted on the next run of this script."

cp $dir/toprc ~/.config/procps/toprc
cp $dir/.gef.rc ~/.gef.rc
